### ISSUE TITLE
I have some question about rewrite

### ISSUE THREAD

**Issue by itoon** [kladd/slim-eloquent#6]
I want to use .htaccess at root because I want to use url with out public 

RewriteEngine On
RewriteBase /email

RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ public/index.php [QSA,L]

It's go to public/index.php unfortunately, it's always go to 
$app->notFound(function () use($app){ 
.....
});

Thank a lot.

**Comment by kladd** [comment]
This rewrite should not be necessary. The `public/` directory should be configured as your root in your apache/nginx/etc web server config file.
